### ISSUE TITLE
Taginfo say that this project display route=historic

### ISSUE THREAD

**Issue by pyrog** [SomeoneElseOSM/mkgmap_style_ajt#1]
[route=historic](https://wiki.openstreetmap.org/wiki/Tag:route%3Dhistoric) seem not supported by your project.

Just remove the following line?
https://github.com/SomeoneElseOSM/mkgmap_style_ajt/blob/edabff8e9c3e9186a907c106a75ab056d4f1eaa6/taginfo_ajt02.json#L259

**Comment by SomeoneElseOSM** [comment]
What taginfo says is this:

https://taginfo.openstreetmap.org/tags/route=historic#projects

That currently shows no consumers of the "route=historic" tag / value combination, but a few consumers of various "route" tags.  In my case it's these types:

    { "key": "route", "value": "bicycle", "description": "Show routes" },
    { "key": "route", "value": "bus", "description": "Show routes" },
    { "key": "route", "value": "ferry", "description": "Show routes" },
    { "key": "route", "value": "foot", "description": "Show routes" },
    { "key": "route", "value": "foot;horse", "description": "Show routes" },
    { "key": "route", "value": "hiking", "description": "Show routes" },
    { "key": "route", "value": "multiaccess", "description": "Show routes" },
    { "key": "route", "value": "subway", "description": "Show routes" },
    { "key": "route", "value": "train", "description": "Show routes" },
    { "key": "route", "value": "tram", "description": "Show routes" },
    { "key": "route", "value": "trolleybus", "description": "Show routes" },
    { "key": "route", "value": "ferry", "description": "Show routes" },

so the main decription:

    { "key": "route", "description": "Show routes" },

can stay, and '"key": "route", "value": "historic"' is correctly not listed.

**Comment by pyrog** [comment]
Unfortunately, for [route=historic](https://taginfo.openstreetmap.org/tags/route=historic#projects) taginfo display that your projects use all values of key route.

Perhaps it is a issue in Taginfo, or rather its [documentation](https://wiki.openstreetmap.org/wiki/Taginfo/Projects) is not clear?

<img width="100%" alt="Taginfo for route=historic" src="https://user-images.githubusercontent.com/2158081/232542494-6e49382b-9d39-4992-b3a2-805400f2fcc4.png">

**Comment by SomeoneElseOSM** [comment]
That's the way that taginfo shows it - see e.g. https://taginfo.openstreetmap.org/tags/route=foot#projects .

I think it makes sense, because not all projects list all values, only the tags.
